# Generated by Django 3.2.5 on 2021-08-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dewdrop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='conditions',
            field=models.ManyToManyField(to='dewdrop.Condition'),
        ),
    ]
